language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_install:
  - composer self-update

install:
  - rm -rf composer.lock
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester -s ./tests/

after_failure:
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
