language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester -s ./tests/

matrix:
  allow_failures:
    - php: nightly

after_failure:
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
