site_name: "Fazette"
site_description: "Extensions for Nette framework."

repo_name: "hermajan/fazette"
repo_url: "https://github.com/hermajan/fazette"

docs_dir: "docs"
site_dir: "docs-html"

markdown_extensions:
    - admonition
    - codehilite:
          linenums: true
    - toc:
          permalink: true
    - fontawesome_markdown
    - pymdownx.details

theme:
    name: "material"
    favicon: "favicon.ico"
    logo: "favicon.ico"
    palette:
        primary: "red"
        accent: "red"

extra_css:
    - "style.css"
    
nav:
    - Home: index.md
    - Bootstrap renderer: bootstrap.md
    - Fa macro: fa.md
    - Forms: forms.md
